; User Editable Variables
; Edit the values below to your likings

[Variables]
; ---------- GENERAL -----------
  ; 0:false, 1:true
  HideTooltip=0
  Font=Segoe UI
  SkinSize=1
  ; This will be called when 'OK' is clicked
  OnOKAction=[!Log "#R#,#G#,#B#"]

; ---------- VALUES ----------
  CurrentTool=G
  H=329
  S=73
  V=95
  R=242
  G=66
  B=156
  Hex=f2429c

; ---------- COLOR PALETTE -----------
  HeaderBarColor=33,33,33
  WindowColor=55,55,55
  WindowColor2=88,88,88
  WindowColor3=111,111,111
  TextColor=255,255,255
